### ISSUE TITLE
[bak] Provide a way to name differently the back-up copy 

### ISSUE THREAD

**Issue by dbitouze** [fniessen/command-line-utilities-leuven#1]
Sometimes it is desirable to create a back-up copy of a file with the same extension, e.g. in order to compare two versions of a file with a software which requires the files to have extension

Some software, which compares files, requires that the files have the same extension (e.g. `diffpdf` for PDF files). So, it would be nice if `bak` would accept an option that gives the back-up copy of "⟨file⟩.⟨ext⟩" the name, for example :

- "bak-⟨file⟩.⟨ext⟩"
- or "old-⟨file⟩.⟨ext⟩"
- or "⟨tilestamp⟩-⟨file⟩.⟨ext⟩".

**Comment by fniessen** [comment]
DONE
